### ISSUE TITLE
Consider making scripts such as pcmsolver.py configuration-state-less

### ISSUE THREAD

**Issue by bast** [PCMSolver/pcmsolver#111]
Currently these scripts are configured where paths to the binary is set at configure time. For context see #110.

Alternatives:
- paths are configurable using CLI at runtime
- use relative paths

Motivation:
- configuration is simpler
- development is simpler since you don't risk modifying a file that is not used or a file that is not tracked

**Comment by bast** [comment]
In other words I think that configuring `foo.py.in` into `foo.py` with absolute paths is an anti-pattern. IMO the better solution is to use either relative paths or receive path information from the outside (CLI).

**Comment by robertodr** [comment]
Fixed in #121
