### ISSUE TITLE
PCMSolver on MS Windows - some tests segfault

### ISSUE THREAD

**Issue by robertodr** [PCMSolver/pcmsolver#14]
Some of the tests are segfaulting on the AppVeyor CI server: 
https://ci.appveyor.com/project/robertodr/pcmsolver/build/83

**Comment by miroi** [comment]
Hi ROberto,

my simple Fortran project, https://github.com/miroi/fortran_input_reader , is giving SegFault on AppVeyor, though the interactive compilation and run on MS Windows Server2012 is fine.

**Comment by robertodr** [comment]
I am closing this issue. I am currently not even able to compile on AppVeyor.
