### ISSUE TITLE
Move metarepo from gitlab to github

### ISSUE THREAD

**Issue by arnfinn** [PCMSolver/pcmsolver#148]
This repo: https://gitlab.com/PCMSolver/pcmsolvermeta

Can, at the moment, only be done by @robertodr or @ilfreddy. @robertodr suggest using [Git LFS](https://git-lfs.github.com/).

**Comment by robertodr** [comment]
You can create repos too now :+1:

**Comment by arnfinn** [comment]
Did the following (for the record):
```
git clone git@gitlab.com:pcmsolver/pcmsolvermeta
cd pcmsolvermeta
git lfs migrate import --include="*.dat" --include-ref=refs/heads/master
git remote add github git@github.com:pcmsolver/pcmsolvermeta
git push -u github master
```

**Comment by robertodr** [comment]
Thanks @arnfinn

**Comment by arnfinn** [comment]
I only included the master branch. Hope that is ok.
