### ISSUE TITLE
import dot has gone again in 1.2.0 release!

### ISSUE THREAD

**Issue by loriab** [PCMSolver/pcmsolver#165]
I believe that the relative dot ` import .pyparsing` added in #164 should be in the v1.2.0 release [here](https://github.com/PCMSolver/pcmsolver/blob/release/1.2/tools/getkw.py#L22)

**Comment by arnfinn** [comment]
It is here #164, not yet merged.

Cherry pick from master

**Comment by loriab** [comment]
But the dot problem was discovered before the release tag. Why mint a tag with a known bug? I know how to get at the commit, was just trying to package pcmsolver from a tag, rather than from a commit or from a tag + patch.

**Comment by arnfinn** [comment]
The release branch was made right before the patch came into `master`, so I believe we just forgot to cherry pick it before the release was minted. Not sure if @robertodr is active today, to make a new release?

**Comment by loriab** [comment]
I think he's back in town tonight. Dropped him a note on psi4/psi4#988 for when he can do a new tag. Just working from my fork now and calling it 1.2.0rc2. Thanks for your help.

**Comment by robertodr** [comment]
Apologies, was too hasty in preparing the tag to catch this one... I'll mint 1.2.1 ASAP

**Comment by arnfinn** [comment]
Fixed here: 3b76ff724
