### ISSUE TITLE
build problem with Psi4

### ISSUE THREAD

**Issue by loriab** [PCMSolver/pcmsolver#21]
Some changes in the past few days have broken the internal cmake build of pcmsolver in psi4. Building against an older version works. See discussion at https://github.com/psi4/psi4private/pull/124#issuecomment-180826563. Maybe should have a git tag at proven version, then ExternalProject in psi4 summons that tag of pcmsolver? The discussion is for branch wavefunction_pass rather than master, but the build system is the one thing that hasn't changed in that branch.

**Comment by robertodr** [comment]
@loriab I minted a new release fixing the problem. You should update the tag in Psi4 to point to this one from now on. Sorry for the trouble.
