### ISSUE TITLE
cmake version

### ISSUE THREAD

**Issue by loriab** [PCMSolver/pcmsolver#22]
Thanks for the `v1.1.0` tag. However, when in psi4 I have `GIT_TAG v1.1.0` (as is presently in psi4/psi4private master), I get this problem building pcmsolver (https://github.com/psi4/psi4private/pull/124#issuecomment-181430744). That's with cmake 3.0.2 . If I update to 3.2 it works fine. If Jet builds it with 3.1.0, it works fine. Perhaps a required cmake version increase is required for both pcmsolver and psi4?

**Comment by robertodr** [comment]
@loriab Sorry for the radio silence. It might be that some older versions of CMake have troubles linking  only object libraries without "real" targets. I unfortunately have to keep the ultra-conservative requirement on CMake version. I will download the 2.8.8 and 3.0.2 executables and try how the build goes.

**Comment by robertodr** [comment]
I can confirm that CMake 2.8.8 doesn't actually work. Trying to troubleshoot the problem.

**Comment by loriab** [comment]
It's really easy to get cmake these days. I just `conda install cmake=3.2` to test the make version hypothesis, if that helps as an argument against "ultra-conservative" requirements.

**Comment by robertodr** [comment]
@loriab it's not me who needs convincing on this point :wink: Being able to require CMake 3.2 would really solve a lot of small hacks in my CMake infrastructure. I have to roll with the requirements of the other QC programs that depend on PCMSolver, which are ultra-conservative (with little chance of convincing...) An update on this issue: 
1. The expansion of a list argument was not handled correctly; 
2. The actual minimal required version is 2.8.9 and not 2.8.8
Pushing a fix soon...

**Comment by robertodr** [comment]
@loriab I finally managed to release a patched version [v1.1.1](https://github.com/PCMSolver/pcmsolver/tree/v1.1.1) I apologize for the amount of time it took me.
