### ISSUE TITLE
loosen test cases in psi4

### ISSUE THREAD

**Issue by loriab** [PCMSolver/pcmsolver#23]
Hi @robertodr, note that I turned off df-scf pre-iterations for pk in psi4, and that naturally jiggled the final digits of scf total energies a bit. In pcm-dft and pcm-scf test cases, you were only converging to 1e-6, but were testing to 1e-8 and 1e-10, so those started failing. I loosened them up in https://github.com/psi4/psi4private/commit/2485238757173ef22d2644dc94ce361ba5eb850c, but you may want to recompute the ref values really tightly, then tighten up the compare_values statements again. Close this issue whenever you're satisfied with the tests; I just wanted to let you know I had altered them.

**Comment by robertodr** [comment]
Thanks for the heads up! Did you file something similar also for Psi4?

**Comment by loriab** [comment]
No, all the psi4 test cases are old enough to have been jiggled before and had to have their comparison criteria aligned with the actual convergence levels. So after the `pk` change, only pcm-scf and pcm-dft broke.
