### ISSUE TITLE
pcmsolver/__init__.py

### ISSUE THREAD

**Issue by loriab** [PCMSolver/pcmsolver#40]
Copied over from psi4/psi4#594 and psi4/psi4#599 discussion

>>> What do you mean by "I'd rather have pcmsolver as a proper module containing init, pcmsolver, getkw, etc., but that would mess with other codes use of pcmsolver, I suspect"?

I meant that it'd be nice to have an installation dir structure like the below where there's an outer pcmsolver module/namespace.
```
here/pcmsolver/
here/pcmsolver/__init__.py
here/pcmsolver/pcmsolver.py
here/pcmsolver/getkw.py
...
```
Then `sys.path('here')` is the operation, and psi4 does `import pcmsolver; pcmsolver.pcmsolver.parse_pcm_input('pcmsolver.inp')` or whatever and all the getkw and codata are within the pcmsolver namespace. At present, one does `sys.path('here/pcmsolver')` and everything's in the outer namespace. The anticipated problem with other codes is that what I want would probably involve some `from . import getkw` and other codes might be depending on the `import getkw` structure.

**Comment by robertodr** [comment]
@bast can you have look at this?

**Comment by bast** [comment]
I will look at it. Currently I am not sure about the scope of work that needs to be done to achieve this. I need to first get an overview of what is there now. Can you give me some pointers of where to start poking? If not, I will use the sources, no problem.

**Comment by bast** [comment]
I think my request is vague. What I meant is a recipe on how to build the Python interface and to reproduce the problem without reading many docs. But of course I can read docs and also read sources.

**Comment by robertodr** [comment]
There is no proper Python interface to build for PCMSolver. The request was to have an `__init__.py` that knows how to import stuff that is used inside `pcmsolver.py`.

**Comment by bast** [comment]
OK thanks I think I understand the issue. Stole the issue from you until further notice :-)

**Comment by bast** [comment]
Now looked a bit more into this. So just to clarify - instead of this (current situation):
```
build/bin/codata.py
build/bin/docopt.py
build/bin/getkw.py
build/bin/pcmsolver.py
build/bin/plot_cavity.py
build/bin/pyparsing.py
build/bin/run_pcm*
build/bin/tmp-pcmsolver-py   <-- what is this btw?
```
we wish to have:
```
build/bin/run_pcm*
build/bin/pcmsolver/__init__.py
build/bin/pcmsolver/codata.py
build/bin/pcmsolver/docopt.py
build/bin/pcmsolver/getkw.py
build/bin/pcmsolver/pcmsolver.py
build/bin/pcmsolver/plot_cavity.py
build/bin/pcmsolver/pyparsing.py
build/bin/pcmsolver/tmp-pcmsolver-py
```

Did I understand the issue correctly?

**Comment by bast** [comment]
... and correspondingly for the install target.

**Comment by robertodr** [comment]
Yes, that is correct. `tmp-pcmsolver-py` is a workaround to configure the file and then copy it into `build/bin` Maybe it's not necessary...

**Comment by bast** [comment]
Thanks! Now I understand I think. I will try to implement the change very soon and also check whether there is a better way to do the `tmp-pcmsolver-py`.

**Comment by robertodr** [comment]
I am sure there is a better way :smile: That line was written a long time ago...

**Comment by bast** [comment]
I have a PR coming up soon. Just running some tests to make sure I did not break stuff.
