### ISSUE TITLE
PCMSolver's support for MS Windows - appveyor CI 

### ISSUE THREAD

**Issue by miroi** [PCMSolver/pcmsolver#7]
Hi Roberto,

would you agree with setting the appveyor.yml CI buildup script for MS Windows ? I would do that first on my branch.

**Comment by robertodr** [comment]
Yes, please go ahead :wink: I signed up for Appveyor, but have had no time to set the YAML file properly.

**Comment by miroi** [comment]
Here is my first attempt - https://github.com/miroi/pcmsolver/blob/appveyor/appveyor.yml 

Hoping I shall adapt the Boost installation according to http://diracprogram.org/doc/master/installation/windows.html

**Comment by miroi** [comment]
Hi,

you can take  https://github.com/miroi/pcmsolver/blob/appveyor/appveyor.yml into master;

however, Boost cmake detection does not work, see  https://testboard.org/cdash/index.php?project=PCMSolver

**Comment by miroi** [comment]
Closing this issue as you are now working with the appveyor.
