### ISSUE TITLE
Compiling error for gcc < 5.1

### ISSUE THREAD

**Issue by arnfinn** [PCMSolver/pcmsolver#76]
The flags ‘-Wsuggest-final-types’, ‘-Wsuggest-final-methods’ and ‘-Wsuggest-override’ introduced in gcc 5.1, but used also for gcc < 5.1

## Expected Behavior
No error

## Current Behavior
Error during compiling:
g++: error: unrecognized command line option ‘-Wsuggest-final-types’
g++: error: unrecognized command line option ‘-Wsuggest-final-methods’
g++: error: unrecognized command line option ‘-Wsuggest-override’

## Possible Solution
 if(CXX_COMPILER_VERSION VERSION_LESS 5.1.0 OR NOT ENABLE_CXX11_SUPPORT)

## Steps to Reproduce (for bugs)
On Stallo
1. module load GCCcore/4.9.3
2. ./setup
3. cd build
4. make

**Comment by bast** [comment]
And I assume that the project supports GCC < 5.1. If we take `.travis-ci.yml` as reference, then yes.

**Comment by robertodr** [comment]
Yes, confirmed as a bug. Apologies for being late on this :smile:

**Comment by bast** [comment]
My goal is to do something like this: http://stackoverflow.com/a/4065761. Better ideas?

**Comment by robertodr** [comment]
That would be a better solution to get the version number. Eventually I wanted to move to a scheme were flags are checked for compatibility with the compiler before being set. I have a semi-working version [here](https://github.com/PCMSolver/ddPCM/blob/master/cmake/custom/compilers/FortranFlags.cmake)

**Comment by bast** [comment]
OK so I will go with the version number first and later we can switch to your scheme. I think I like it.

**Comment by robertodr** [comment]
I think it should be safer and should lead to cleaner CMake code. On the other hand, I can't quite decide if compiler flags should be set globally or on a per-target basis.

**Comment by bast** [comment]
For me globally (when the globe is the library) if possible, and per target if needed.

**Comment by robertodr** [comment]
I would then remove the `summary.cmake` from [here](https://github.com/PCMSolver/pcmsolver/blob/release/1.Y/cmake/autocmake.yml#L56) since the information is possibly unreliable.

**Comment by bast** [comment]
What is the target branch for a fix?

**Comment by robertodr** [comment]
`release/1.Y` I would then update `master` by cherry-picking.

**Comment by bast** [comment]
OK let me know if it went to the wrong branch, I can easily relocate.
