### ISSUE TITLE
Directory for buildup scripts ?

### ISSUE THREAD

**Issue by miroi** [PCMSolver/pcmsolver#9]
Hi Roberto,

I see you are running CDash tests, https://testboard.org/cdash/index.php?project=PCMSolver&date=2015-10-21 .

I would welcome a dedicated directory for CDash buildup scripts, so that I can run also "my" buildup scripts (MS Windows, IBM, Linux with PGI etc) from there.

**Comment by robertodr** [comment]
Access granted on this repository: https://gitlab.com/PCMSolver/pcmsolvermeta
I keep my recipes there. Please make a directory with the machine name (and/or any meaningful identifier)

**Comment by robertodr** [comment]
Closing.
