### ISSUE TITLE
correct rpath definition

### ISSUE THREAD

**Issue by ilfreddy** [PCMSolver/pcmsolver#90]
## Expected Behavior
The libpcm library used by PCMSolver should be the one freshly compiled, rather than the default one in /usr/local/lib

## Current Behavior
I had libpcm.dylib in /usr/local/lib which was used instead of the one just compiled.
Once the libpcm.dlyb in /usr/local/lib was removed, the latest one (pcmsolver/build/lib) was used instead, yielding the correct code behavior.

**Comment by robertodr** [comment]
Can you print the contents of the relevant CMake variables and post them here?

**Comment by robertodr** [comment]
Coming back to this issue, can you do a fresh build and run `otool -L bin/run_pcm`?

**Comment by ilfreddy** [comment]
I have merged the RPATH issue. I will recompile and run `otool` asap

**Comment by ilfreddy** [comment]
Besides the version number, it sems to work:
`bin/run_pcm:
	/Users/luca/programs/pcmsolver_upstream/build/lib/libpcm.1.dylib (compatibility version 1.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)`

**Comment by robertodr** [comment]
And if you install the project? What does `otool` say for `<install_prefix>/bin/run_pcm`?

**Comment by ilfreddy** [comment]
1) make install copies a lot of headers in /usr/lib 
2) `otool -L bin/run_pcm` gives the same outcome after make install
3) should I use other options to otool?

**Comment by robertodr** [comment]
You should have set a local prefix like `--prefix=$HOME/tmp/pcmsolver`. Can you post the output of `otool -L $HOME/tmp/pcmsolver`?

**Comment by ilfreddy** [comment]
At which stage did I have to do that?

**Comment by robertodr** [comment]
Configuration, but it doesn't matter. It's just that if you installed locally, you just need to wipe the installed directory afterwards to "uninstall". Now you have stuff on system path lying around that might cause trouble later, plus you needed to run `sudo`.

**Comment by ilfreddy** [comment]
I did not run no sudo...

**Comment by robertodr** [comment]
How could you write to `/usr/lib` without `sudo`? Mysteries of Mac...

**Comment by ilfreddy** [comment]
seems I "own" local, lib and include under /usr/lib

**Comment by bast** [comment]
I did not know that Mac allows that. Scary :-)
